// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// earcut_cpp
IntegerVector earcut_cpp(NumericVector x, NumericVector y, IntegerVector holes, IntegerVector numholes);
RcppExport SEXP _decido_earcut_cpp(SEXP xSEXP, SEXP ySEXP, SEXP holesSEXP, SEXP numholesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type holes(holesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type numholes(numholesSEXP);
    rcpp_result_gen = Rcpp::wrap(earcut_cpp(x, y, holes, numholes));
    return rcpp_result_gen;
END_RCPP
}
// earcut_sfg
IntegerVector earcut_sfg(SEXP& sfg);
RcppExport SEXP _decido_earcut_sfg(SEXP sfgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP& >::type sfg(sfgSEXP);
    rcpp_result_gen = Rcpp::wrap(earcut_sfg(sfg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_decido_earcut_cpp", (DL_FUNC) &_decido_earcut_cpp, 4},
    {"_decido_earcut_sfg", (DL_FUNC) &_decido_earcut_sfg, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_decido(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
