# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' dopey
#'
#' dopey description
#'
#' dopey details
#' @param x -ordinate
#' @param y -ordinate
#' @export
#' @examples
#' dopey(1, 2)
#' x <- c(0, 0, 0.75, 1, 0.5, 0.8, 0.69)
#' y <- c(0, 1, 1, 0.8, 0.7, 0.6, 0)
#' dopey(x, y)
dopey <- function(x, y) {
    .Call(`_dopey_cpp_dopey`, x, y)
}

